name: enso_pipeline
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pyresample
  - numpy
  - pyyaml
  - netcdf4
  - requests
  - xarray=0.16.2
  - matplotlib=3.5.2
  - h5py
  - scipy
  - cartopy=0.20.3
  - dask
  - pandas=1.3.5
  - shapely=1.7.1
  - font-ttf-ubuntu
  - shapely=1.8.2